# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca263a9d2e382dc481bc34315710d3ea2a3cd885c1c9688e6a882b809dcde1fd42fc0df80fba8013038204877a8a7841c8f31dd2e45eb587fac1c3ce4d01f48

test:
  secret_key_base: 8abb48bec7c9d1b6a3eeb771192c3159c2c8408b9e80b1133f4984eae63c2c5259e8d105f9196208ed22340c602323fdba5ae00633fd08faf923adfbba1ed1ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
